[build]
  functions = "netlify/functions"
  command = "npm run build"

[dev]
  command = "node server.js"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
